[project]
name = "multi-area-model"
version = "1.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["."]
include = ["multiarea_model*"]
namespaces = false
